name: Sync to Perforce
on:
  push:
    branches:
      - main
jobs:
  sync-to-perforce:
    runs-on: gitconn
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Sync and Push to Perforce
      run: |
        log() {
          local type="$1"
          shift
          echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')] [$type] $*"
        }

        check_error() {
          if [ $? -ne 0 ]; then
            log "ERROR" "$1"
            exit 1
          fi
        }

        log "INFO" "Setup GitHub repo"
        cd ..
        if [ -d "clonedir" ]; then
          log "INFO" "Removing existing clonedir directory"
          rm -rf clonedir
          check_error "Failed to remove existing clonedir directory"
        fi
        git clone https://github.com/Trivenik1015/git-connector-test-repo.git clonedir
        check_error "Failed to clone GitHub repo"
        sleep 5
        cd clonedir
        log "INFO" "Setup GitConnector repo"
        ls -lrt
        sleep 5
        git remote -v
        echo "$P4USER"
        echo "$P4PASSWD"
        echo "Test line"
        ENCODED_P4PASSWD=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$P4PASSWD'''))")
        git remote set-url --push origin https://"$P4USER":"$ENCODED_P4PASSWD"@bealcisqa01.ad.skynet:9443/testgraphdepot/testrepo.git
        check_error "Failed to set remote URL"
        sleep 5
        echo "List remote repo after the change"
        git remote -v
        sleep 5
        log "INFO" "Push changes to GitConnector repo"
        git push
        check_error "Failed to push changes to GitConnector repo"
        ls -lrt
      env:
        P4PORT: ${{ secrets.P4_PORT }}
        P4USER: ${{ secrets.KATTAT_P4_USERNAME }}
        P4PASSWD: ${{ secrets.KATTAT_P4_PWD }}
